# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.10.12
    - name: Lint with flake8
      run: |
        pdm add flake8
        # stop the build if there are Python syntax errors or undefined names
        pdm run flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pdm run flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with tox/pytest & generate coverage badge
      run: |
        pdm add tox
        pdm run tox
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: tests/badge
          branch: gh-pages
